### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by veive** [SebLague/Procedural-Landmass-Generation#1]
Hey Sebastian,

What are the licensing terms for the code in the series?

**Comment by SebLague** [comment]
There is no license. Attribution is appreciated, however. 

   

 On Thursday, February 25, 2016 7:55 PM, veive <notifications@github.com> wrote:
 

 Hey Sebastian,What are the licensing terms for the code in the series?—

**Comment by lightningrock** [comment]
Unlicensed code is problematic for use.  By default unlicensed code is all rights reserved.

https://softwareengineering.stackexchange.com/questions/276144/using-unlicensed-code
