### ISSUE TITLE
Chunks dont line up

### ISSUE THREAD

**Issue by BlueDev5** [SebLague/Procedural-Landmass-Generation#29]
the chunks dont line up even after the episode 21 fixing gaps

**Comment by Merse06** [comment]
> the chunks dont line up even after the episode 21 fixing gaps

I have the same problem. Could you fix it? Because I would be happy, if you could help me, to solve my problem.

**Comment by Merse06** [comment]
It's because you are generating your terrain on Local mode, not Global. If you use Global, it will line up :)
