### ISSUE TITLE
Going through the floor

### ISSUE THREAD

**Issue by Neirpyc** [SebLague/Procedural-Landmass-Generation#5]
As you can see on the video below, i managed to find a spot on a map where I glitch through the ground.

[Unity 5.6.0f3 Personal (64bit) - Scene.unity - Proc Gen E21 - PC, Mac & Linux Standalone_ _DX11_ 24_06_2017 17_12_23.mp4.zip](https://github.com/SebLague/Procedural-Landmass-Generation/files/1099844/Unity.5.6.0f3.Personal.64bit.-.Scene.unity.-.Proc.Gen.E21.-.PC.Mac.Linux.Standalone_._DX11_.24_06_2017.17_12_23.mp4.zip)

**Comment by lifeofllama** [comment]
Not gonna open that file but try turning LOD's down to 0 for every distance. Stopped me from going through the ground!

**Comment by erebuswolf** [comment]
The collision meshes were broken in E20 during the refactor. He never tested running around in the terrain outside the base mesh. I'm looking to create a pull request to fix it.

**Comment by erebuswolf** [comment]
I figured it out @Neirpyc the viewer element of the Map Generator in the E21 project isn't the RigidBodyFPSController. So select the map generator and drag the RigidBodyFPSController object to the Viewer element in the inspector to link them. Then you should stop falling through the floor.

**Comment by Dramier** [comment]
On the off chance anyone stumbles across this problem with the collision meshes not being generated, here's how to fix it:   In TerrainChunk.cs, in the UpdateCollisionMesh() function, find this line:
float sqrDstFromViewerToEdge = bounds.SqrDistance (viewerPosition);

Change it to:
float sqrDstFromViewerToEdge = Mathf.Sqrt (bounds.SqrDistance (viewerPosition));

This makes the distance values much smaller and closer to what they should be for when it assigns collision meshes to chunks the player is walking near.   Then at the top of the TerrainChunk class, find the line for const float colliderGenerationDistanceThreshold and adjust it up higher from the value of 5 it is probably at for you up to something like 15.    That should get it pretty close and without causing too much lag.   

This may not be the correct way to fix it, but it is working fine for me.   Hope this helps somebody who gets stuck on this problem.
